name: changelog-add-on-comment

on:
  issue_comment:
    types:
      - "created"

permissions: {}

jobs:
  save-comment:
    if: >
      github.event.issue.pull_request != null &&
      startsWith(github.event.comment.body, '/changelog')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Acknowledge comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "eyes",
            })

      - name: Save event metadata
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const fs = require('fs')
            const body = context.payload.comment.body
            const prNumber = context.payload.issue.number
            const replace = body.startsWith('/changelog replace')
            fs.mkdirSync('artifacts', { recursive: true })
            fs.writeFileSync('artifacts/pr-number', String(prNumber))
            fs.writeFileSync('artifacts/comment-body', body.slice(0, 2048))
            fs.writeFileSync('artifacts/replace', String(replace))

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: changelog-${{ github.event.issue.number }}-${{ github.run_id }}
          path: artifacts/
