name: PR - golangci-lint

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "synchronize"
    paths:
      - ".github/workflows/**"
      - "**.go"
      - ".golangci.yml"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2
